# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HistorySanitizer < Formula
  desc "Tool to sanitize shell history content"
  homepage "https://github.com/arnac-io/history-sanitizer"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arnac-io/history-sanitizer/releases/download/v0.1.0/history-sanitizer_Darwin_x86_64.tar.gz"
      sha256 "946b95622ba5a269c26b4cf607c08dc2f189255065c2e8ae3bdb273459fa440f"

      def install
        bin.install "history-sanitizer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arnac-io/history-sanitizer/releases/download/v0.1.0/history-sanitizer_Darwin_arm64.tar.gz"
      sha256 "76e26e59a95ff82ce97655c4f44d67b6d5908f259f84fc5409d8e6388ed6c417"

      def install
        bin.install "history-sanitizer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arnac-io/history-sanitizer/releases/download/v0.1.0/history-sanitizer_Linux_x86_64.tar.gz"
      sha256 "b43bcead37825270913c6a0231f38a2e5b7e171019401635675c648fa5314bec"
      def install
        bin.install "history-sanitizer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arnac-io/history-sanitizer/releases/download/v0.1.0/history-sanitizer_Linux_arm64.tar.gz"
      sha256 "7db549fe39f1fb243fe200ffe14a0e3935e8e90bd1833ac2c3f0eec61114009f"
      def install
        bin.install "history-sanitizer"
      end
    end
  end

  test do
    system "#{bin}/history-sanitizer --help"
  end
end
