# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HistorySanitizer < Formula
  desc "Tool to sanitize shell history content"
  homepage "https://github.com/arnac-io/history-sanitizer"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arnac-io/history-sanitizer/releases/download/v0.1.0/history-sanitizer_Darwin_x86_64.tar.gz"
      sha256 "1197cf4229fa39614c37747845cba2fc82bbe5a70df56490e57833f0875b5100"

      def install
        bin.install "history-sanitizer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arnac-io/history-sanitizer/releases/download/v0.1.0/history-sanitizer_Darwin_arm64.tar.gz"
      sha256 "25c7f736e16a6fe47507f9b1e0fab81bed9971e6a53d87fc9feca87adfe205b9"

      def install
        bin.install "history-sanitizer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arnac-io/history-sanitizer/releases/download/v0.1.0/history-sanitizer_Linux_x86_64.tar.gz"
      sha256 "07ecbf533378d79e63c8b49b6e5dd66b6512dfb3dbd81cd4e113c54b742df59b"
      def install
        bin.install "history-sanitizer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arnac-io/history-sanitizer/releases/download/v0.1.0/history-sanitizer_Linux_arm64.tar.gz"
      sha256 "889ace2e46f7cab2cfe89433558908fb8bab4fb8a22f5ecd9b860cbb9f061138"
      def install
        bin.install "history-sanitizer"
      end
    end
  end

  test do
    system "#{bin}/history-sanitizer --help"
  end
end
